const app=document.getElementById('app');
const KEY='jeePhysicsMockHistoryV1';
let state=null;
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const clean=QUESTIONS.filter(q=>!q.flagged);
const chapters=[...new Set(clean.map(q=>q.chapter))];
const fmt=n=>String(Math.max(0,n)).padStart(2,'0');
function history(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function saveHistory(x){const h=history();h.unshift(x);localStorage.setItem(KEY,JSON.stringify(h.slice(0,10)))}
function norm(s){return String(s??'').trim().replace(/\s+/g,'').replace(/,/g,'').toLowerCase()}
function sameAns(a,b){const x=norm(a),y=norm(b);if(x===y)return true;const nx=Number(x),ny=Number(y);return Number.isFinite(nx)&&Number.isFinite(ny)&&Math.abs(nx-ny)<1e-9}
function selectQuestions(n=80){
 const used=new Set((history()[0]?.ids)||[]);
 const pools=chapters.map(ch=>({ch,pool:clean.filter(q=>q.chapter===ch&&!used.has(q.id))}));
 // Fall back to the full chapter pool when avoiding the previous paper would leave too few questions.
 pools.forEach(x=>{if(x.pool.length===0)x.pool=clean.filter(q=>q.chapter===x.ch)});
 const totalPool=pools.reduce((a,x)=>a+x.pool.length,0);
 n=Math.max(1,Math.min(n,totalPool));
 const counts=Object.fromEntries(chapters.map(c=>[c,0]));
 const exact=pools.map(x=>({ch:x.ch,raw:n*x.pool.length/totalPool,base:Math.floor(n*x.pool.length/totalPool),frac:(n*x.pool.length/totalPool)%1}));
 exact.forEach(x=>counts[x.ch]=x.base);
 let left=n-exact.reduce((a,x)=>a+x.base,0);
 exact.sort((a,b)=>b.frac-a.frac);
 for(let i=0;i<left;i++)counts[exact[i%exact.length].ch]++;
 let out=[];
 for(const x of pools){let pool=x.pool;const take=Math.min(counts[x.ch],pool.length);out.push(...shuffle(pool).slice(0,take));}
 // If rounding/caps left us short, fill from remaining unique questions.
 if(out.length<n){const ids=new Set(out.map(q=>q.id));const rest=shuffle(clean.filter(q=>!ids.has(q.id)&&!used.has(q.id)));out.push(...rest.slice(0,n-out.length));}
 return shuffle(out.slice(0,n));
}
function renderStart(){
 const total=clean.length;
 app.innerHTML=`<div class="wrap"><div class="top"><div class="brand"><h1>JEE Main Physics — Class 11 PYQ Simulator</h1><p>Built from the uploaded JEE Main 2025 PYQ PDF · ${total} usable questions</p></div><div class="row"><button class="btn secondary" id="hist">History</button></div></div>
 <div class="grid"><div class="card"><h2>Build your test</h2><div class="stats"><div class="stat"><span class="muted">Questions</span><b id="previewN">80</b></div><div class="stat"><span class="muted">Time limit</span><b>None</b></div><div class="stat"><span class="muted">Scoring</span><b>+4 / −1</b></div><div class="stat"><span class="muted">Pool</span><b>${total}</b></div></div><p class="muted">Choose exactly how many questions you want. There is <b>no countdown and no time pressure</b>. The paper remains PYQ-only and is selected proportionally across the available Class 11 chapters.</p><div class="row"><label>Number of questions <input id="mainQn" type="number" min="1" max="${total}" value="80" style="width:100px;background:#0d1527;color:white;border:1px solid var(--border);padding:8px;border-radius:8px"></label><button class="btn" id="start">Start test</button><button class="btn secondary" id="custom">Choose chapters</button></div><div class="section"><h3>Current distribution preview</h3><table class="dist"><tr><th>Chapter</th><th>Q</th><th>Pool</th><th></th></tr>${chapters.map(c=>`<tr><td>${c}</td><td><b class="dcount" data-ch="${c}">—</b></td><td>${clean.filter(q=>q.chapter===c).length}</td><td><div class="bar"><span></span></div></td></tr>`).join('')}</table></div></div>
 <div class="card"><h2>What you get</h2><ul class="muted"><li>Original PYQ question images — diagrams preserved</li><li>Choose any test length from 1 to ${total}</li><li>No timer — take the test at your own pace</li><li>Randomized paper and question order</li><li>Answer + mark-for-review palette</li><li>Post-test chapter analysis</li><li>Incorrect/skipped question review</li><li>Local history for your previous mocks</li></ul><h3>Source flags</h3><p class="small muted">${FLAGGED.length} questions were flagged by the PDF's own answer-key notes/ambiguities and are not used in the default paper.</p></div></div></div>`;
 const updatePreview=()=>{const n=Math.max(1,Math.min(total,+document.getElementById('mainQn').value||80));document.getElementById('previewN').textContent=n;const weights=chapters.map(c=>({c,p:clean.filter(q=>q.chapter===c).length}));const sum=weights.reduce((a,x)=>a+x.p,0);const counts=Object.fromEntries(weights.map(x=>[x.c,Math.floor(n*x.p/sum)]));let left=n-Object.values(counts).reduce((a,b)=>a+b,0);weights.sort((a,b)=>(n*b.p/sum)%1-(n*a.p/sum)%1);for(let i=0;i<left;i++)counts[weights[i%weights.length].c]++;document.querySelectorAll('.dcount').forEach(e=>e.textContent=counts[e.dataset.ch]||0)};
 document.getElementById('mainQn').oninput=updatePreview; updatePreview();
 document.getElementById('start').onclick=()=>{const n=Math.max(1,Math.min(total,+document.getElementById('mainQn').value||80));startTest(selectQuestions(n))};
 document.getElementById('custom').onclick=customModal;
 document.getElementById('hist').onclick=showHistory;
}
function customModal(){
 app.innerHTML=`<div class="wrap"><div class="top"><div class="brand"><h1>Custom Test</h1><p>Choose the chapters and exactly how many questions you want. There is no timer.</p></div><button class="btn secondary" onclick="renderStart()">Back</button></div><div class="card"><div class="row"><label>Questions <input id="qn" type="number" min="1" max="${clean.length}" value="40" style="width:90px;background:#0d1527;color:white;border:1px solid var(--border);padding:8px;border-radius:8px"></label><span class="muted">No time limit</span></div><div class="section">${chapters.map((c,i)=>`<label style="display:block;margin:10px 0"><input type="checkbox" class="ch" value="${i}" checked> ${c} <span class="muted small">(${clean.filter(q=>q.chapter===c).length})</span></label>`).join('')}</div><button class="btn" id="go">Create test</button></div></div>`;
 document.getElementById('go').onclick=()=>{const sel=[...document.querySelectorAll('.ch:checked')].map(x=>chapters[+x.value]);if(!sel.length){alert('Select at least one chapter.');return}let pool=clean.filter(q=>sel.includes(q.chapter));const n=Math.max(1,Math.min(pool.length,+document.getElementById('qn').value||40));const chosen=shuffle(pool).slice(0,n);startTest(chosen)};
}
function startTest(qs){state={qs,index:0,answers:Array(qs.length).fill(''),review:Array(qs.length).fill(false),spent:Array(qs.length).fill(0),last:Date.now(),started:Date.now(),submitted:false};renderTest()}
function addSpent(){if(!state)return;const now=Date.now();state.spent[state.index]+=Math.max(0,Math.round((now-state.last)/1000));state.last=now}
function renderTest(){const q=state.qs[state.index];app.innerHTML=`<div class="wrap"><div class="top"><div class="brand"><h1>Class 11 Physics Mock</h1><p>Question ${state.index+1} of ${state.qs.length} · PYQ ${q.attempt} 2025 · ${q.chapter}</p></div><div class="badge">UNTIMED</div></div><div class="test"><main class="card"><div class="qmeta"><div><span class="badge">${q.chapter}</span> <span class="badge">${q.attempt} Attempt · Q${q.question_no}</span></div><span class="muted small">Source PDF page ${q.source_page}</span></div><img class="qimg" src="${q.image}" alt="Question ${state.index+1}"><div class="answerbox"><label class="small muted">Answer — enter option number (1–4) or numerical value</label><input id="ans" autocomplete="off" value="${state.answers[state.index]||''}" placeholder="Your answer"></div><div class="row section"><button class="btn secondary" id="prev" ${state.index===0?'disabled':''}>Previous</button><button class="btn secondary" id="clear">Clear</button><button class="btn secondary" id="review">${state.review[state.index]?'Unmark review':'Mark for review'}</button><button class="btn" id="next">${state.index===state.qs.length-1?'Finish':'Next'}</button></div></main><aside class="card"><h3>Question palette</h3><div class="palette">${state.qs.map((x,i)=>`<button class="pbtn ${i===state.index?'current':''} ${state.answers[i]!==''?'answered':''} ${state.review[i]?'review':''}" data-i="${i}">${i+1}</button>`).join('')}</div><div class="legend"><span><i class="dot" style="background:#1a5a42"></i>Answered</span><span><i class="dot" style="background:#ffc857"></i>Review</span></div><hr style="border-color:var(--border);border-width:1px 0 0;margin:16px 0"><button class="btn danger" id="submit">Submit test</button><p class="muted small">Do not submit until you are ready. Answers are hidden until submission.</p></aside></div></div>`;
 const inp=document.getElementById('ans');inp.focus();inp.oninput=e=>{state.answers[state.index]=e.target.value};
 document.getElementById('prev').onclick=()=>{addSpent();if(state.index>0){state.index--;state.last=Date.now();renderTest()}};
 document.getElementById('next').onclick=()=>{addSpent();if(state.index===state.qs.length-1)submitTest(false);else{state.index++;state.last=Date.now();renderTest()}};
 document.getElementById('clear').onclick=()=>{state.answers[state.index]='';renderTest()};
 document.getElementById('review').onclick=()=>{state.review[state.index]=!state.review[state.index];renderTest()};
 document.querySelectorAll('.pbtn').forEach(b=>b.onclick=()=>{addSpent();state.index=+b.dataset.i;state.last=Date.now();renderTest()});
 document.getElementById('submit').onclick=()=>{if(confirm('Submit the test now? You will see the answer key and analysis after submission.'))submitTest(false)};
}
function submitTest(auto){if(state.submitted)return;addSpent();state.submitted=true;const rows=state.qs.map((q,i)=>{const ok=sameAns(state.answers[i],q.answer);return {...q,user:state.answers[i],ok,spent:state.spent[i]}});const correct=rows.filter(x=>x.ok).length,attempted=rows.filter(x=>norm(x.user)!=='').length,wrong=attempted-correct,score=correct*4-wrong;const result={date:new Date().toISOString(),score,correct,wrong,unattempted:rows.length-attempted,accuracy:attempted?correct/attempted:0,attemptRate:attempted/rows.length,ids:rows.map(x=>x.id),rows};saveHistory(result);renderResults(result,auto)}
function renderResults(r,auto){const by={};r.rows.forEach(x=>{by[x.chapter]??={a:0,c:0,w:0,u:0,s:0};by[x.chapter].a++;if(x.user==='')by[x.chapter].u++;else if(x.ok)by[x.chapter].c++;else by[x.chapter].w++;by[x.chapter].s+=x.ok?4:(x.user===''?0:-1)});const mistakes=r.rows.filter(x=>!x.ok);app.innerHTML=`<div class="wrap"><div class="top"><div class="brand"><h1>Test Analysis</h1><p>Untimed test · ${new Date(r.date).toLocaleString()}</p></div><button class="btn" onclick="renderStart()">New test</button></div><div class="card"><div class="resultgrid"><div class="stat"><span class="muted">Score</span><b>${r.score}</b><span class="muted">/ ${r.rows.length*4}</span></div><div class="stat"><span class="muted">Correct</span><b class="good">${r.correct}</b></div><div class="stat"><span class="muted">Wrong</span><b class="bad">${r.wrong}</b></div><div class="stat"><span class="muted">Unattempted</span><b>${r.unattempted}</b></div></div><div class="stats section"><div class="stat"><span class="muted">Accuracy</span><b>${(r.accuracy*100).toFixed(1)}%</b></div><div class="stat"><span class="muted">Attempt rate</span><b>${(r.attemptRate*100).toFixed(1)}%</b></div><div class="stat"><span class="muted">Avg time/Q</span><b>${Math.round(r.rows.reduce((a,x)=>a+x.spent,0)/r.rows.length)}s</b></div><div class="stat"><span class="muted">Time used</span><b>${Math.floor(r.rows.reduce((a,x)=>a+x.spent,0)/60)}m</b></div></div></div><div class="card section"><h2>Chapter performance</h2><table class="table"><tr><th>Chapter</th><th>Attempted</th><th>Correct</th><th>Wrong</th><th>Accuracy</th><th>Score</th></tr>${Object.entries(by).map(([c,v])=>`<tr><td>${c}</td><td>${v.a-v.u}</td><td class="good">${v.c}</td><td class="bad">${v.w}</td><td>${v.a-v.u?((v.c/(v.a-v.u))*100).toFixed(1):'0.0'}%</td><td>${v.s}</td></tr>`).join('')}</table></div><div class="card section"><h2>Incorrect & skipped questions (${mistakes.length})</h2>${mistakes.length?mistakes.map((x,i)=>`<div class="mistake"><div class="row" style="justify-content:space-between"><b>Q${r.rows.indexOf(x)+1} · ${x.chapter}</b><span class="badge">${x.attempt} 2025 · source p.${x.source_page}</span></div><p class="small"><b>Your answer:</b> ${x.user||'Not attempted'} · <b>Correct:</b> ${x.answer}</p><p class="small muted">Time: ${x.spent}s · This is the original PYQ image; use it to review the exact setup/diagram.</p><img src="${x.image}"></div>`).join(''):'<p class="muted">Perfect attempt — nothing to review here.</p>'}</div><div class="card section"><h2>Quick diagnosis</h2><p>${diagnosis(by,r)}</p></div></div>`}
function diagnosis(by,r){const arr=Object.entries(by).map(([c,v])=>({c,acc:(v.a-v.u)?v.c/(v.a-v.u):1,wrong:v.w})).sort((a,b)=>a.acc-b.acc);const slow=[...r.rows].sort((a,b)=>b.spent-a.spent).slice(0,3);let s=`You attempted ${r.correct+r.wrong}/${r.rows.length} questions. `;if(arr.length)s+=`Lowest chapter accuracy: <b>${arr[0].c}</b> (${(arr[0].acc*100).toFixed(1)}%). `;if(slow[0])s+=`Longest individual time: <b>Q${r.rows.indexOf(slow[0])+1}</b> at ${slow[0].spent}s (${slow[0].chapter}).`;return s}
function showHistory(){const h=history();app.innerHTML=`<div class="wrap"><div class="top"><div class="brand"><h1>Mock History</h1><p>Stored locally in this browser.</p></div><button class="btn secondary" onclick="renderStart()">Back</button></div><div class="card">${h.length?h.map((r,i)=>`<div class="history-item"><b>Test ${h.length-i}</b> · ${new Date(r.date).toLocaleString()}<br><span class="muted">Score ${r.score}/${r.rows.length*4} · Accuracy ${(r.accuracy*100).toFixed(1)}% · ${r.correct} correct · ${r.wrong} wrong · ${r.unattempted} unattempted</span></div>`).join(''):'<p class="muted">No tests yet.</p>'}</div></div>`}
renderStart();
